### ISSUE TITLE
Fram size

### ISSUE THREAD

**Issue by geologic** [rose53/RingBuffer#2]
Hi

I want to try your library with FRAM MR44V100A, that has 128K.
In RingBuffer.cpp you have:

`const uint16_t RingBuffer::bootSectorStart  = 32 * 1024 - bootSectorSize;`

I assume 32 is the kb size of the memory, that's correct? 
Do you think it will work with 128k?

Regards

**Comment by rose53** [comment]
> 
> 
> Hi
> 
> I want to try your library with FRAM MR44V100A, that has 128K.
> In RingBuffer.cpp you have:
> 
> `const uint16_t RingBuffer::bootSectorStart = 32 * 1024 - bootSectorSize;`
> 
> I assume 32 is the kb size of the memory, that's correct?
> Do you think it will work with 128k?
> 
> Regards

Hi,
yes, the 32 * 1024 is the size in kB. In my opinion it should work. You should have a look to the dump method, there seems to be a value in the for loop for 32kb

Let me know, if it worked for you.

Sorry, pressed close by accident.
